ARG GOLANG_BASE=docker.io/library/golang:1.25-alpine
ARG RUNTIME_BASE=gcr.io/distroless/static-debian12:nonroot

FROM ${GOLANG_BASE} AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/login ./cmd/server

FROM ${RUNTIME_BASE}

ARG AUTHOR
ARG VERSION
LABEL maintainer=${AUTHOR} version=${VERSION}

COPY --from=build /out/login /login
EXPOSE 8088
USER nonroot:nonroot
ENTRYPOINT ["/login"]
